apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  annotations: 
    kubernetes.io/change-cause: v1 deployment
spec:
  minReadySeconds: 5
  replicas: 4
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - nginx
          - web
          - apache
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels: 
        app: web
    spec:
      containers:
        - name: http
          image: nginx 
          resources: 
            requests: 
              cpu: 100m
              memory: 64M
            limits:
              cpu: 150m
              memory: 128M
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          startupProbe:
            initialDelaySeconds: 1
            periodSeconds: 2
            successThreshold: 1
            failureThreshold: 2
            tcpSocket:
              port: 80
          livenessProbe:
            initialDelaySeconds: 1
            periodSeconds: 2
            successThreshold: 1
            failureThreshold: 2
            httpGet:
              path: /
              port: 80
          readinessProbe: 
            initialDelaySeconds: 1
            periodSeconds: 2
            successThreshold: 1
            failureThreshold: 2 
            timeoutSeconds: 5
            httpGet:
              path: /
              port: 80


